name: grade-portal-be-go-2
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted 
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: false
        - name: Login Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  
        # Bước 3: Thiết lập Docker Buildx
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
          id: buildx
  
        # Bước 4: Build và đẩy Docker image hỗ trợ ARM64
        - name: Build and push Docker image for ARM64
          uses: docker/build-push-action@v6
          id: docker_build
          with:
            context: ./src           # Đặt build context là thư mục src
            file: ./src/Dockerfile   # Đường dẫn đến tệp Dockerfile bên trong thư mục src
            builder: ${{ steps.buildx.outputs.name }}
            platforms: linux/arm64   # Xây dựng image cho kiến trúc ARM64
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/grade-portal-be-go-2:latest
        # Bước 5: Kiểm tra kết quả
        - name: Verify
          run: echo ${{ steps.docker_build.outputs.digest }}